### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by lunDreame** [laz-/bestintcp#2]
I'm installing it, but let me ask you a few questions. Currently, I succeeded in adding configuration.yaml to the homeassist file editor. I'm not sure after that, but I can't find the bestin element in the integrated component.
![IMG_1154](https://user-images.githubusercontent.com/87955512/149620632-efdb6e11-ab67-429c-aaa7-f1a5a6006b5a.jpg)
![IMG_1155](https://user-images.githubusercontent.com/87955512/149620646-c40c00c6-435b-4bb3-8613-b30d211845ab.jpg)

**Comment by laz-** [comment]
You've got to insert a device into the private Bestin network to relay the requests. I posted some photos in the thread at https://cafe.naver.com/koreassistant/1160

If you're not comfortable putting this box into the nework, I'd perhaps recommend looking into the Bestin v2.0 stuff at https://cafe.naver.com/stsmarthome/41048. I could look at expanding that to support the 1.0 protocol. That's an approach that I originally took, but HA was querying too quickly and overwhelmed the internet facing gateway. It took a few weeks before someone noticed and restarted it. It looks like the 2.0 code is polling at 120 seconds, so probably slow enough to not kill the gateway.

**Comment by lunDreame** [comment]
![image](https://user-images.githubusercontent.com/87955512/151699431-81b2d31a-cc05-4d04-8e12-5ed291662a2c.jpeg)

**Comment by lunDreame** [comment]
I sat like this, but I keep getting errors. I wonder if that's the right way to add the yaml file and if the ip address for the yaml command is the bestin wallpad ip.

**Comment by leoincedo** [comment]
Adding manifest.json seems to make it work.
